import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import type { EmitCatalog, CatalogEvent } from "../../types/index.js";

export function readCatalog(filePath: string): EmitCatalog {
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `Catalog file not found: ${filePath}\n` +
        "  Run `emit scan` first to generate the catalog."
    );
  }
  const content = fs.readFileSync(filePath, "utf8");
  const parsed = yaml.load(content) as EmitCatalog;
  if (!parsed || typeof parsed !== "object" || !parsed.events) {
    throw new Error(`Invalid catalog format: ${filePath}`);
  }
  return parsed;
}

export function writeCatalog(filePath: string, catalog: EmitCatalog): void {
  const parts: string[] = [];

  // Header fields
  parts.push("# emit event catalog — generated by emit scan. Edit carefully; emit scan will update this file.");
  parts.push("# Docs: https://github.com/emit-io/emit");
  parts.push(yaml.dump({
    version: catalog.version,
    generated_at: catalog.generated_at,
    commit: catalog.commit,
  }, { lineWidth: 120 }).trimEnd());

  // Stats
  parts.push("\n# ── Stats ───────────────────────────────────────────────────────────────────");
  parts.push("# How many events were scanned, located in code, and their confidence breakdown.");
  parts.push(yaml.dump({ stats: catalog.stats }, { lineWidth: 120 }).trimEnd());

  // Property definitions
  parts.push("\n# ── Property Definitions ────────────────────────────────────────────────────");
  parts.push("# Canonical definitions for properties that appear across multiple events.");
  parts.push("# Deviations note where a specific event's usage differs from the shared definition.");
  parts.push(yaml.dump({ property_definitions: catalog.property_definitions }, { lineWidth: 120 }).trimEnd());

  // Events — blank line between each entry for scannability
  parts.push("\n# ── Events ──────────────────────────────────────────────────────────────────");
  parts.push("# Full catalog of tracked events. Each entry includes:");
  parts.push("#   description / fires_when  — what the event means and when it fires");
  parts.push("#   confidence                — how certain emit is about the extraction (high/medium/low)");
  parts.push("#   source_file / source_line — where the tracking call lives in code");
  parts.push("#   properties                — each property sent with the event");
  parts.push("#   flags                     — anything worth a human review");
  const eventsRaw = yaml.dump({ events: catalog.events }, { lineWidth: 120 }).trimEnd();
  // Insert a blank line before each event key (lines indented exactly 2 spaces)
  parts.push(eventsRaw.replace(/\n(  [^ ])/g, "\n\n$1"));

  // Resolved (renamed/refactored events found by deep search)
  if (catalog.resolved && catalog.resolved.length > 0) {
    parts.push("\n# ── Resolved ────────────────────────────────────────────────────────────────");
    parts.push("# Events that were missing but found under a different name via deep search.");
    parts.push("#   original_name     — the name from your event list");
    parts.push("#   actual_event_name — the name as it appears in code");
    parts.push("#   rename_detected   — true if this looks like a deliberate rename");
    const resolvedRaw = yaml.dump({ resolved: catalog.resolved }, { lineWidth: 120 }).trimEnd();
    parts.push(resolvedRaw.replace(/\n(- original_name:)/g, "\n\n$1"));
  }

  // Not found
  parts.push("\n# ── Not Found ───────────────────────────────────────────────────────────────");
  parts.push("# Events that were in your event list but could not be located in the codebase.");
  parts.push(yaml.dump({ not_found: catalog.not_found ?? [] }, { lineWidth: 120 }).trimEnd());

  parts.push("");
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, parts.join("\n"));
}

export function getEvent(
  catalog: EmitCatalog,
  eventName: string
): CatalogEvent | undefined {
  return catalog.events[eventName];
}

export function updateEvent(
  catalog: EmitCatalog,
  eventName: string,
  event: CatalogEvent
): EmitCatalog {
  return {
    ...catalog,
    events: {
      ...catalog.events,
      [eventName]: event,
    },
  };
}

export function catalogExists(filePath: string): boolean {
  return fs.existsSync(filePath);
}
