import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import type { EmitCatalog, CatalogEvent, PropertyDefinition } from "../../types/index.js";

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Convert an event name to a filesystem-safe slug for use as a filename.
 * Deterministic: same input always produces same output.
 */
export function slugifyEventName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Returns true if the output path represents a directory-based catalog
 * (i.e. does NOT end with .yml or .yaml).
 */
export function isCatalogDirectory(filePath: string): boolean {
  const ext = path.extname(filePath).toLowerCase();
  return ext !== ".yml" && ext !== ".yaml";
}

// ── Single-file I/O (existing behavior) ────────────────────────────────────

function readCatalogFile(filePath: string): EmitCatalog {
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `Catalog file not found: ${filePath}\n` +
        "  Run `emit scan` first to generate the catalog."
    );
  }
  const content = fs.readFileSync(filePath, "utf8");
  const parsed = yaml.load(content) as EmitCatalog;
  if (!parsed || typeof parsed !== "object" || !parsed.events) {
    throw new Error(`Invalid catalog format: ${filePath}`);
  }
  return parsed;
}

function writeCatalogFile(filePath: string, catalog: EmitCatalog): void {
  const parts: string[] = [];

  // Header fields
  parts.push("# emit event catalog — generated by emit scan. Edit carefully; emit scan will update this file.");
  parts.push("# Docs: https://github.com/emit-io/emit");
  parts.push(yaml.dump({
    version: catalog.version,
    generated_at: catalog.generated_at,
    commit: catalog.commit,
  }, { lineWidth: 120 }).trimEnd());

  // Stats
  parts.push("\n# ── Stats ───────────────────────────────────────────────────────────────────");
  parts.push("# How many events were scanned, located in code, and their confidence breakdown.");
  parts.push("# Confidence levels (event-level scoring; per-property scoring uses the same scale):");
  parts.push("#   high   — verified: track/fire call visible AND trigger context clear");
  parts.push("#   medium — justified read but one piece of evidence missing (acceptable)");
  parts.push("#   low    — critical evidence missing; needs human review");
  // Default to {} when stats is missing — yaml.dump({ stats: undefined }) emits
  // a bare "{}" that breaks round-trip parsing when followed by more content.
  parts.push(yaml.dump({ stats: catalog.stats ?? {} }, { lineWidth: 120 }).trimEnd());

  // Property definitions
  parts.push("\n# ── Property Definitions ────────────────────────────────────────────────────");
  parts.push("# Canonical definitions for properties that appear across multiple events.");
  parts.push("# Deviations note where a specific event's usage differs from the shared definition.");
  parts.push(yaml.dump({ property_definitions: catalog.property_definitions ?? {} }, { lineWidth: 120 }).trimEnd());

  // Events — blank line between each entry for scannability
  parts.push("\n# ── Events ──────────────────────────────────────────────────────────────────");
  parts.push("# Full catalog of tracked events. Each entry includes:");
  parts.push("#   description / fires_when  — what the event means and when it fires");
  parts.push("#   confidence                — how certain emit is about the extraction (high/medium/low)");
  parts.push("#   source_file / source_line — where the tracking call lives in code");
  parts.push("#   properties                — each property sent with the event");
  parts.push("#   flags                     — anything worth a human review");

  // Sort events: parents first, then sub-events grouped after their parent
  const eventNames = Object.keys(catalog.events);
  const sortedNames = sortEventsWithSubEvents(eventNames, catalog.events);
  const sortedEvents: Record<string, CatalogEvent> = {};
  for (const name of sortedNames) {
    sortedEvents[name] = catalog.events[name];
  }

  const eventsRaw = yaml.dump({ events: sortedEvents }, { lineWidth: 120 }).trimEnd();
  // Insert a blank line before each event key (lines indented exactly 2 spaces)
  let eventsFormatted = eventsRaw.replace(/\n(  [^ ])/g, "\n\n$1");

  // Insert sub-event group comments
  const subEventGroups = getSubEventGroups(catalog.events);
  for (const [parentName, property] of subEventGroups) {
    const escapedParent = parentName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const commentLine = `\n  # ── Sub-events of ${parentName} (discriminator: ${property}) ──`;
    // Find the first sub-event key after the parent and insert comment before it
    const firstSubPattern = new RegExp(`(\n\n)(  ${escapedParent}\\.)`);
    eventsFormatted = eventsFormatted.replace(firstSubPattern, `\n${commentLine}\n\n$2`);
  }

  parts.push(eventsFormatted);

  // Resolved (renamed/refactored events found by deep search)
  if (catalog.resolved && catalog.resolved.length > 0) {
    parts.push("\n# ── Resolved ────────────────────────────────────────────────────────────────");
    parts.push("# Events that were missing but found under a different name via deep search.");
    parts.push("#   original_name     — the name from your event list");
    parts.push("#   actual_event_name — the name as it appears in code");
    parts.push("#   rename_detected   — true if this looks like a deliberate rename");
    const resolvedRaw = yaml.dump({ resolved: catalog.resolved }, { lineWidth: 120 }).trimEnd();
    parts.push(resolvedRaw.replace(/\n(- original_name:)/g, "\n\n$1"));
  }

  // Not found
  parts.push("\n# ── Not Found ───────────────────────────────────────────────────────────────");
  parts.push("# Events that were in your event list but could not be located in the codebase.");
  parts.push(yaml.dump({ not_found: catalog.not_found ?? [] }, { lineWidth: 120 }).trimEnd());

  parts.push("");
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, parts.join("\n"));
}

// ── Directory-based I/O ────────────────────────────────────────────────────

function readCatalogDirectory(dirPath: string): EmitCatalog {
  const indexPath = path.join(dirPath, "_index.yml");
  if (!fs.existsSync(indexPath)) {
    throw new Error(
      `Catalog directory not found: ${dirPath}\n` +
        "  Run `emit scan` first to generate the catalog."
    );
  }

  const indexContent = fs.readFileSync(indexPath, "utf8");
  const index = yaml.load(indexContent) as Omit<EmitCatalog, "events"> & { events?: Record<string, CatalogEvent> };
  if (!index || typeof index !== "object") {
    throw new Error(`Invalid catalog index format: ${indexPath}`);
  }

  // Read individual event files
  const eventsDir = path.join(dirPath, "events");
  const events: Record<string, CatalogEvent> = {};

  if (fs.existsSync(eventsDir)) {
    const eventFiles = fs.readdirSync(eventsDir)
      .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
      .sort();

    for (const file of eventFiles) {
      const content = fs.readFileSync(path.join(eventsDir, file), "utf8");
      const parsed = yaml.load(content) as Record<string, CatalogEvent>;
      if (parsed && typeof parsed === "object") {
        // Each file has one top-level key: the event name
        for (const [eventName, eventData] of Object.entries(parsed)) {
          events[eventName] = eventData;
        }
      }
    }
  }

  return {
    version: index.version,
    generated_at: index.generated_at,
    commit: index.commit,
    stats: index.stats,
    property_definitions: index.property_definitions ?? {},
    events,
    not_found: index.not_found ?? [],
    resolved: index.resolved,
  } as EmitCatalog;
}

function writeCatalogDirectory(dirPath: string, catalog: EmitCatalog): void {
  const eventsDir = path.join(dirPath, "events");
  fs.mkdirSync(eventsDir, { recursive: true });

  // Write _index.yml (everything except events)
  const indexParts: string[] = [];
  indexParts.push("# emit event catalog index — generated by emit scan.");
  indexParts.push("# Docs: https://github.com/emit-io/emit");
  indexParts.push(yaml.dump({
    version: catalog.version,
    generated_at: catalog.generated_at,
    commit: catalog.commit,
  }, { lineWidth: 120 }).trimEnd());

  indexParts.push("\n# ── Stats ───────────────────────────────────────────────────────────────────");
  indexParts.push(yaml.dump({ stats: catalog.stats ?? {} }, { lineWidth: 120 }).trimEnd());

  indexParts.push("\n# ── Property Definitions ────────────────────────────────────────────────────");
  indexParts.push(yaml.dump({ property_definitions: catalog.property_definitions ?? {} }, { lineWidth: 120 }).trimEnd());

  if (catalog.resolved && catalog.resolved.length > 0) {
    indexParts.push("\n# ── Resolved ────────────────────────────────────────────────────────────────");
    const resolvedRaw = yaml.dump({ resolved: catalog.resolved }, { lineWidth: 120 }).trimEnd();
    indexParts.push(resolvedRaw.replace(/\n(- original_name:)/g, "\n\n$1"));
  }

  indexParts.push("\n# ── Not Found ───────────────────────────────────────────────────────────────");
  indexParts.push(yaml.dump({ not_found: catalog.not_found ?? [] }, { lineWidth: 120 }).trimEnd());

  indexParts.push("");
  fs.writeFileSync(path.join(dirPath, "_index.yml"), indexParts.join("\n"));

  // Write individual event files + track slugs for collision detection and orphan cleanup
  const slugToName = new Map<string, string>();
  const writtenFiles = new Set<string>();

  for (const [eventName, eventData] of Object.entries(catalog.events)) {
    let slug = slugifyEventName(eventName);

    // Handle slug collisions
    if (slugToName.has(slug) && slugToName.get(slug) !== eventName) {
      let suffix = 2;
      while (slugToName.has(`${slug}-${suffix}`)) suffix++;
      console.warn(
        `[emit] Slug collision: "${eventName}" and "${slugToName.get(slug)}" both map to "${slug}". Using "${slug}-${suffix}".`
      );
      slug = `${slug}-${suffix}`;
    }
    slugToName.set(slug, eventName);

    const fileName = `${slug}.yml`;
    writtenFiles.add(fileName);

    const eventParts: string[] = [];
    eventParts.push(`# ${eventName}`);
    eventParts.push(yaml.dump({ [eventName]: eventData }, { lineWidth: 120 }).trimEnd());
    eventParts.push("");
    fs.writeFileSync(path.join(eventsDir, fileName), eventParts.join("\n"));
  }

  // Orphan cleanup: remove event files no longer in catalog
  if (fs.existsSync(eventsDir)) {
    for (const file of fs.readdirSync(eventsDir)) {
      if ((file.endsWith(".yml") || file.endsWith(".yaml")) && !writtenFiles.has(file)) {
        fs.unlinkSync(path.join(eventsDir, file));
      }
    }
  }
}

// ── Public API ─────────────────────────────────────────────────────────────

export function readCatalog(filePath: string): EmitCatalog {
  if (isCatalogDirectory(filePath)) {
    return readCatalogDirectory(filePath);
  }
  return readCatalogFile(filePath);
}

export function writeCatalog(filePath: string, catalog: EmitCatalog): void {
  if (isCatalogDirectory(filePath)) {
    writeCatalogDirectory(filePath, catalog);
  } else {
    writeCatalogFile(filePath, catalog);
  }
}

export function getEvent(
  catalog: EmitCatalog,
  eventName: string
): CatalogEvent | undefined {
  return catalog.events[eventName];
}

export function updateEvent(
  catalog: EmitCatalog,
  eventName: string,
  event: CatalogEvent
): EmitCatalog {
  return {
    ...catalog,
    events: {
      ...catalog.events,
      [eventName]: event,
    },
  };
}

export function catalogExists(filePath: string): boolean {
  if (isCatalogDirectory(filePath)) {
    return fs.existsSync(path.join(filePath, "_index.yml"));
  }
  return fs.existsSync(filePath);
}

// ── Single-event I/O (for future MCP optimization) ────────────────────────

export function readSingleEvent(
  catalogPath: string,
  eventName: string
): { event: CatalogEvent; propertyDefinitions: Record<string, PropertyDefinition> } | null {
  if (!isCatalogDirectory(catalogPath)) {
    // Fall back to full read for single-file mode
    const catalog = readCatalog(catalogPath);
    const event = catalog.events[eventName];
    return event ? { event, propertyDefinitions: catalog.property_definitions } : null;
  }

  const indexPath = path.join(catalogPath, "_index.yml");
  if (!fs.existsSync(indexPath)) return null;

  const index = yaml.load(fs.readFileSync(indexPath, "utf8")) as any;
  const propertyDefinitions = index?.property_definitions ?? {};

  // Try the direct slug first
  const slug = slugifyEventName(eventName);
  const eventFile = path.join(catalogPath, "events", `${slug}.yml`);

  if (fs.existsSync(eventFile)) {
    const parsed = yaml.load(fs.readFileSync(eventFile, "utf8")) as Record<string, CatalogEvent>;
    if (parsed?.[eventName]) {
      return { event: parsed[eventName], propertyDefinitions };
    }
  }

  // Slug collision fallback: scan event files for the name
  const eventsDir = path.join(catalogPath, "events");
  if (!fs.existsSync(eventsDir)) return null;

  for (const file of fs.readdirSync(eventsDir)) {
    if (!file.endsWith(".yml") && !file.endsWith(".yaml")) continue;
    const parsed = yaml.load(fs.readFileSync(path.join(eventsDir, file), "utf8")) as Record<string, CatalogEvent>;
    if (parsed?.[eventName]) {
      return { event: parsed[eventName], propertyDefinitions };
    }
  }

  return null;
}

export function writeSingleEvent(
  catalogPath: string,
  eventName: string,
  event: CatalogEvent,
  catalogMeta: Pick<EmitCatalog, "generated_at">
): void {
  if (!isCatalogDirectory(catalogPath)) {
    // For single-file mode, must do a full read-modify-write
    const catalog = readCatalog(catalogPath);
    const updated = updateEvent(catalog, eventName, event);
    updated.generated_at = catalogMeta.generated_at;
    writeCatalog(catalogPath, updated);
    return;
  }

  const slug = slugifyEventName(eventName);
  const eventsDir = path.join(catalogPath, "events");
  fs.mkdirSync(eventsDir, { recursive: true });

  // Write the event file
  const eventParts: string[] = [];
  eventParts.push(`# ${eventName}`);
  eventParts.push(yaml.dump({ [eventName]: event }, { lineWidth: 120 }).trimEnd());
  eventParts.push("");
  fs.writeFileSync(path.join(eventsDir, `${slug}.yml`), eventParts.join("\n"));

  // Update _index.yml timestamp
  const indexPath = path.join(catalogPath, "_index.yml");
  if (fs.existsSync(indexPath)) {
    const content = fs.readFileSync(indexPath, "utf8");
    const index = yaml.load(content) as any;
    if (index) {
      index.generated_at = catalogMeta.generated_at;
      // Rewrite index preserving structure
      const indexParts: string[] = [];
      indexParts.push("# emit event catalog index — generated by emit scan.");
      indexParts.push("# Docs: https://github.com/emit-io/emit");
      indexParts.push(yaml.dump({
        version: index.version,
        generated_at: index.generated_at,
        commit: index.commit,
      }, { lineWidth: 120 }).trimEnd());
      indexParts.push("\n# ── Stats ───────────────────────────────────────────────────────────────────");
      indexParts.push(yaml.dump({ stats: index.stats ?? {} }, { lineWidth: 120 }).trimEnd());
      indexParts.push("\n# ── Property Definitions ────────────────────────────────────────────────────");
      indexParts.push(yaml.dump({ property_definitions: index.property_definitions ?? {} }, { lineWidth: 120 }).trimEnd());
      if (index.resolved && index.resolved.length > 0) {
        indexParts.push("\n# ── Resolved ────────────────────────────────────────────────────────────────");
        indexParts.push(yaml.dump({ resolved: index.resolved }, { lineWidth: 120 }).trimEnd());
      }
      indexParts.push("\n# ── Not Found ───────────────────────────────────────────────────────────────");
      indexParts.push(yaml.dump({ not_found: index.not_found ?? [] }, { lineWidth: 120 }).trimEnd());
      indexParts.push("");
      fs.writeFileSync(indexPath, indexParts.join("\n"));
    }
  }
}

// ── Sub-event sorting helpers ─────────────────────────────────────────────

function sortEventsWithSubEvents(
  names: string[],
  events: Record<string, CatalogEvent>
): string[] {
  const parents: string[] = [];
  const subsByParent = new Map<string, string[]>();

  for (const name of names) {
    const ev = events[name];
    if (ev.parent_event) {
      const subs = subsByParent.get(ev.parent_event) ?? [];
      subs.push(name);
      subsByParent.set(ev.parent_event, subs);
    } else {
      parents.push(name);
    }
  }

  const sorted: string[] = [];
  for (const parent of parents) {
    sorted.push(parent);
    const subs = subsByParent.get(parent);
    if (subs) {
      subs.sort();
      sorted.push(...subs);
    }
  }

  // Add any orphaned sub-events (parent not in catalog)
  for (const [, subs] of subsByParent) {
    for (const sub of subs) {
      if (!sorted.includes(sub)) sorted.push(sub);
    }
  }

  return sorted;
}

function getSubEventGroups(
  events: Record<string, CatalogEvent>
): [string, string][] {
  const groups = new Map<string, string>();
  for (const ev of Object.values(events)) {
    if (ev.parent_event && ev.discriminator_property && !groups.has(ev.parent_event)) {
      groups.set(ev.parent_event, ev.discriminator_property);
    }
  }
  return [...groups.entries()];
}
